// themes.js
export const dashboardThemes = {
  light: {
    name: 'Light',
    droppableBgColor: '#f8f8f8',
    fontColor: '#000000',
    fontStyleState: 'normal',
    fontSize: '32',
    headingColor: '#333333',
  },
  dark: {
    name: 'Dark',
    droppableBgColor: '#1e1e1e',
    fontColor: '#ffffff',
    fontStyleState: 'normal',
    fontSize: '32',
    headingColor: '#ffffff',
  },
  ocean: {
    name: 'Ocean Blue',
    droppableBgColor: '#e0f7fa',
    fontColor: '#00796b',
    fontStyleState: 'italic',
    fontSize: '30',
    headingColor: '#004d40',
  },
  sunset: {
    name: 'Sunset',
    droppableBgColor: '#fff3e0',
    fontColor: '#e65100',
    fontStyleState: 'bold',
    fontSize: '34',
    headingColor: '#bf360c',
  },
  forest: {
    name: 'Forest',
    droppableBgColor: '#e8f5e9',
    fontColor: '#2e7d32',
    fontStyleState: 'italic bold',
    fontSize: '30',
    headingColor: '#1b5e20',
  },
  midnight: {
    name: 'Midnight',
    droppableBgColor: '#121212',
    fontColor: '#bb86fc',
    fontStyleState: 'normal',
    fontSize: '32',
    headingColor: '#3700b3',
  },
  lavender: {
    name: 'Lavender',
    droppableBgColor: '#f3e5f5',
    fontColor: '#6a1b9a',
    fontStyleState: 'italic',
    fontSize: '30',
    headingColor: '#4a148c',
  },
  sunrise: {
    name: 'Sunrise',
    droppableBgColor: '#ffe0b2',
    fontColor: '#ef6c00',
    fontStyleState: 'bold',
    fontSize: '34',
    headingColor: '#e65100',
  },
  desert: {
    name: 'Desert',
    droppableBgColor: '#fff8e1',
    fontColor: '#a1887f',
    fontStyleState: 'normal',
    fontSize: '31',
    headingColor: '#6d4c41',
  },
  glacier: {
    name: 'Glacier',
    droppableBgColor: '#e0f2f1',
    fontColor: '#004d40',
    fontStyleState: 'italic',
    fontSize: '30',
    headingColor: '#00695c',
  },
  coral: {
    name: 'Coral',
    droppableBgColor: '#ffccbc',
    fontColor: '#d84315',
    fontStyleState: 'bold',
    fontSize: '33',
    headingColor: '#bf360c',
  },
  mint: {
    name: 'Mint',
    droppableBgColor: '#e0f2f1',
    fontColor: '#00796b',
    fontStyleState: 'normal',
    fontSize: '30',
    headingColor: '#004d40',
  },
  rose: {
    name: 'Rose',
    droppableBgColor: '#fce4ec',
    fontColor: '#c2185b',
    fontStyleState: 'italic',
    fontSize: '32',
    headingColor: '#880e4f',
  },
  steel: {
    name: 'Steel',
    droppableBgColor: '#eceff1',
    fontColor: '#37474f',
    fontStyleState: 'bold',
    fontSize: '31',
    headingColor: '#263238',
  },
  lemon: {
    name: 'Lemon',
    droppableBgColor: '#fffde7',
    fontColor: '#fbc02d',
    fontStyleState: 'italic',
    fontSize: '32',
    headingColor: '#f57f17',
  },
  cherry: {
    name: 'Cherry',
    droppableBgColor: '#fce4ec',
    fontColor: '#ad1457',
    fontStyleState: 'bold',
    fontSize: '34',
    headingColor: '#880e4f',
  },
  sky: {
    name: 'Sky',
    droppableBgColor: '#e1f5fe',
    fontColor: '#0277bd',
    fontStyleState: 'italic',
    fontSize: '30',
    headingColor: '#01579b',
  },
  cocoa: {
    name: 'Cocoa',
    droppableBgColor: '#efebe9',
    fontColor: '#4e342e',
    fontStyleState: 'normal',
    fontSize: '32',
    headingColor: '#3e2723',
  },
  plum: {
    name: 'Plum',
    droppableBgColor: '#f3e5f5',
    fontColor: '#6a1b9a',
    fontStyleState: 'bold',
    fontSize: '33',
    headingColor: '#4a148c',
  },
  grass: {
    name: 'Grass',
    droppableBgColor: '#f1f8e9',
    fontColor: '#33691e',
    fontStyleState: 'italic bold',
    fontSize: '30',
    headingColor: '#1b5e20',
  },
  ice: {
    name: 'Ice',
    droppableBgColor: '#e0f7fa',
    fontColor: '#006064',
    fontStyleState: 'normal',
    fontSize: '32',
    headingColor: '#004d40',
  },
  amber: {
    name: 'Amber',
    droppableBgColor: '#fff8e1',
    fontColor: '#ff6f00',
    fontStyleState: 'bold',
    fontSize: '33',
    headingColor: '#e65100',
  },
  graphite: {
    name: 'Graphite',
    droppableBgColor: '#cfd8dc',
    fontColor: '#212121',
    fontStyleState: 'normal',
    fontSize: '32',
    headingColor: '#37474f',
  },
  denim: {
    name: 'Denim',
    droppableBgColor: '#e3f2fd',
    fontColor: '#0d47a1',
    fontStyleState: 'italic',
    fontSize: '31',
    headingColor: '#1565c0',
  },
  blush: {
    name: 'Blush',
    droppableBgColor: '#f8bbd0',
    fontColor: '#880e4f',
    fontStyleState: 'bold italic',
    fontSize: '34',
    headingColor: '#ad1457',
  },
  nature: {
  name: 'Nature',
//   droppableBgColor: '#ffffff',
  fontColor: '#003300',
  fontStyleState: 'italic',
  fontSize: '32',
  wallpaper: process.env.PUBLIC_URL + '/wallpapers/3A-Vision_v7.jpg',
},
space: {
  name: 'Space',
//   droppableBgColor: '#000000',
  fontColor: '#ffffff',
  fontStyleState: 'bold',
  fontSize: '34',
  wallpaper: process.env.PUBLIC_URL + '/wallpapers/space.jpg',
}
,
  custom: {
    name: 'Custom',
    droppableBgColor: '#ffffff',
    fontColor: '#000000',
    fontStyleState: 'normal',
    fontSize: '32',
    headingColor: '#333333',
  },
};
